# Generated by Django 4.2.1 on 2023-05-29 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('build_up_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carpet_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('parking', models.BooleanField(default=False)),
                ('property_on', models.CharField(max_length=255)),
                ('listed_on', models.DateTimeField(auto_now_add=True)),
                ('bachelors_allowed', models.BooleanField(default=True)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pet_allowed', models.BooleanField(default=False)),
                ('non_vegetarian', models.BooleanField(default=True)),
                ('property_description', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='homescout.user')),
            ],
        ),
    ]
