# Generated by Django 4.2.1 on 2023-05-30 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homescout', '0005_alter_property_listed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
