# Generated by Django 4.2.1 on 2023-05-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homescout', '0006_alter_property_listed_by'),
    ]

    operations = [
    ]
